on:
  push:
    branches: [ master, feature/**]
jobs:
  laravel-test-with-database:
    runs-on: ubuntu-latest
    # service container for mysql database image

    services:
      mysql-service:
        image:  mysql:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Prepare The Environment
        run: cp .env.example .env

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, dom, fileinfo, mysql
          coverage: xdebug

      - name: Laravel Setup
        run: |
          composer install --no-progress --prefer-dist --optimize-autoloader
          php artisan key:generate
          chmod -R 777 storage bootstrap/cache

      - name: Clear Config
        run: php artisan config:clear

      - name: Run Migration
        run: php artisan migrate -v
        env:
          DB_PORT: ${{ job.services.mysql.ports['3306'] }}

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: learning
          DB_PORT: 33306
          DB_USER: root
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          BROADCAST_DRIVER: log
          CACHE_DRIVER: redis
          QUEUE_CONNECTION: redis
          SESSION_DRIVER: redis
        run: |
          php artisan migrate
          vendor/phpunit/phpunit/phpunit


